# Generated by Django 4.0.1 on 2022-01-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Areaid', models.IntegerField()),
                ('Areanombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empleadoid', models.IntegerField()),
                ('Empleadonom', models.CharField(max_length=50)),
                ('Empleadoape', models.CharField(max_length=50)),
                ('Areaid', models.IntegerField()),
                ('SubArid', models.IntegerField()),
                ('TipoDoceid', models.IntegerField()),
                ('Empleadodoc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubAr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubArid', models.IntegerField()),
                ('SubArnom', models.CharField(max_length=50)),
                ('Areaid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoDoce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoDoceid', models.IntegerField()),
                ('TipoDocenom', models.CharField(max_length=50)),
            ],
        ),
    ]
