# Generated by Django 4.0.1 on 2022-01-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='Areaid',
            field=models.IntegerField(verbose_name='Cod.Area'),
        ),
        migrations.AlterField(
            model_name='areas',
            name='Areanombre',
            field=models.CharField(max_length=50, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='Empleadoape',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='Empleadoid',
            field=models.IntegerField(verbose_name='Cod.Empleado'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='Empleadonom',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='subar',
            name='Areaid',
            field=models.IntegerField(verbose_name='Cod.Area'),
        ),
        migrations.AlterField(
            model_name='subar',
            name='SubArid',
            field=models.IntegerField(verbose_name='Cod.Sub Area'),
        ),
        migrations.AlterField(
            model_name='subar',
            name='SubArnom',
            field=models.CharField(max_length=50, verbose_name='Sub-Area'),
        ),
        migrations.AlterField(
            model_name='tipodoce',
            name='TipoDocenom',
            field=models.CharField(max_length=50, verbose_name='Tipo de Documento'),
        ),
    ]
