# Generated by Django 4.0.1 on 2022-01-16 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0002_alter_areas_areaid_alter_areas_areanombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areas',
            options={'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='subar',
            options={'verbose_name': 'Sub-Area', 'verbose_name_plural': 'Sub-Areas'},
        ),
        migrations.AlterField(
            model_name='subar',
            name='Areaid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='RRHH.areas'),
        ),
    ]
