# Generated by Django 4.0.1 on 2022-01-16 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0004_alter_empleados_options_alter_empleados_areaid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodoce',
            options={'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documentos'},
        ),
        migrations.AlterField(
            model_name='empleados',
            name='TipoDoceid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='RRHH.tipodoce'),
        ),
        migrations.AlterField(
            model_name='subar',
            name='Areaid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='RRHH.areas', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='subar',
            name='SubArid',
            field=models.IntegerField(verbose_name='Cod.Sub-Area'),
        ),
    ]
