# Generated by Django 4.0.1 on 2022-01-16 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0005_alter_tipodoce_options_alter_empleados_tipodoceid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='Areaid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='RRHH.areas', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='SubArid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='RRHH.subar', verbose_name='Sub-Area'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='TipoDoceid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='RRHH.tipodoce', verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='tipodoce',
            name='TipoDoceid',
            field=models.IntegerField(verbose_name='Cod.Tipo de Documento'),
        ),
    ]
